export enum MessageType {

    CONNECT = 'CONNECT',
    DISCONNECT = 'DISCONNECT',
    CAMERA_CONNECT = 'CAMERA_CONNECT',
    CAMERA_DISCONNECT = 'CAMERA_DISCONNECT',
    CAMERA_RECORDING_START = 'CAMERA_RECORDING_START',
    CAMERA_RECORDING_STOP = 'CAMERA_RECORDING_STOP',

}
