apiVersion: apps/v1
kind: Deployment
metadata:
    name: $APP
    labels:
        app: $APP
spec:
    selector:
        matchLabels:
            app: $APP
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: $APP
        spec:
            containers:
                - image: $IMAGE
                  name: $APP
                  ports:
                      - containerPort: $PORT
                        name: http
                  readinessProbe:
                      httpGet:
                          path: /
                          port: $PORT
                      initialDelaySeconds: 1
                      timeoutSeconds: 1
                  livenessProbe:
                      httpGet:
                          path: /
                          port: $PORT
                      initialDelaySeconds: 5
                      timeoutSeconds: 5
                  resources:
                      requests:
                          cpu: "5m"
                          memory: 5Mi
